query ($mediaId: Int, $userId: Int, $type: MediaType) {
  MediaList(mediaId: $mediaId, userId: $userId, type: $type) {
    id
    mediaId
    status
    score
    progress
    createdAt
    updatedAt
  }
}
