# https://github.com/rust-lang/rust/blob/master/.github/workflows/ci.yml
# https://github.com/launchbadge/sqlx/blob/master/.github/workflows/sqlx.yml
# https://github.com/dh1tw/remoteAudio/blob/master/.github/workflows/build.yml
# TODO: Set CRATE_NAME to match the project name
name: mendo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  format:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --verbose

  test:
    if: "!contains(github.event.head_commit.message, 'ci skip') && contains(github.event.head_commit.message, 'ci test')"
    name: Unit Test

    steps:
      - name: Set CRATE_NAME
        id: set_crate_name
        run: echo ::set-output name=CRATE_NAME::mendo

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        env:
          CRATE_NAME: ${{ steps.set_crate_name.outputs.CRATE_NAME }}
        with:
          command: test
          args: --manifest-path $CRATE_NAME/Cargo.toml

  check:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: CI Check
    runs-on: ubuntu-latest
    steps:
      - name: Set CRATE_NAME
        id: set_crate_name
        run: echo ::set-output name=CRATE_NAME::mendo

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-check-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        env:
          CRATE_NAME: ${{ steps.set_crate_name.outputs.CRATE_NAME }}
        with:
          command: build
          args: --manifest-path $CRATE_NAME/Cargo.toml --bin $CRATE_NAME

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # Basically include only tier 1 platforms
        # can also specific OS args for each of these targets. See 2nd link.
        include:
          - os: ubuntu-latest
            target: [x86_64-unknown-linux-gnu, i686-unknown-linux-gnu]
            bin: target/release/${{ steps.set_crate_name.outputs.CRATE_NAME }}
          - os: windows-latest
            target: [x86_64-pc-windows-msvc, x86_64-pc-windows-gnu, i686-pc-windows-msvc, i686-pc-windows-gnu]
            bin: target/release/${{ steps.set_crate_name.outputs.CRATE_NAME }}.exe
          - os: macOS-latest
            target: x86_64-apple-darwin
            bin: target/release/${{ steps.set_crate_name.outputs.CRATE_NAME }}

    steps:
      - name: Set CRATE_NAME
        id: set_crate_name
        run: echo ::set-output name=CRATE_NAME::mendo

      - name: Get VERSION
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-release-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        env:
          CRATE_NAME: ${{ steps.set_crate_name.outputs.CRATE_NAME }}
        with:
          command: build
          args: --release --manifest-path $CRATE_NAME/Cargo.toml --bin $CRATE_NAME

      - uses: edgarrc/action-7z@v1.0.4
        env:
          CRATE_NAME: ${{ steps.set_crate_name.outputs.CRATE_NAME }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        with:
          args: 7z a -t7z $CRATE_NAME-$VERSION-${{ matrix.target}}.7z ${{ matrix.bin }}

      - name: Prepare artifact
        id: prepare_artifact
        env:
          CRATE_NAME: ${{ steps.set_crate_name.outputs.CRATE_NAME }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo ::set-output name=ARTIFACT_PATH::./$CRATE_NAME-$VERSION-${{ matrix.target }}.7z
          echo ::set-output name=ARTIFACT_NAME::$CRATE_NAME-$VERSION-${{ matrix.target }}.7z

      - uses: actions/create-release@v1
        id: create_release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: false

      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.prepare_artifact.outputs.ARTIFACT_PATH }}
          asset_name: ${{ steps.prepare_artifact.outputs.ARTIFACT_NAME }}
          asset_content_type: application/x-7z-compressed
